version: '3.9'

services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - eureka-network


  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8000"
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
    networks:
      - eureka-network
    deploy:
      replicas: 3
    depends_on:
      - eureka-server


  service-discovery:
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - eureka-network
    depends_on:
      - eureka-server
  

  microservice-client-new:
    build:
      context: ./microservice-client-new
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - eureka-network
    depends_on:
      - eureka-server

  
  microservice-client-old:
    build:
      context: ./microservice-client-old
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - eureka-network
    depends_on:
      - eureka-server


networks:
  eureka-network:
    driver: bridge
